name: kanboard
services:
  app: # read the KANBOARD_IMAGE from .env, or default to `:latest` tag
    image: kanboard/kanboard:v1.2.48
    container_name: kanboard
    restart: always
    networks:
      - proxy
      - internal
    # traefik uses docker DNS service to disocover kanboard
    # and use the ports it excpects. no need for port mapping
    volumes:
      - data:/var/www/app/data
      - plugins:/var/www/app/plugins
      # - certs:/etc/nginx/ssl
      # kanboard runs nginx and exposes both http and https. with traefik as rproxy (L7), no need for cert management
    environment:
      # `postgress://` is the protocol, `kanboard:kanboard-secret` is the login:password for DB
      # `db` is the hostname in docker (`db` is the service name), and `\kanboard` is the database name
      DATABASE_URL: postgres://kanboard:kanboard-secret@db/kanboard
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanboard.rule=Host(`kanboard.${VPS_DOMAIN}`)"
      - "traefik.http.routers.kanboard.entrypoints=websecure"
      - "traefik.http.routers.kanboard.tls=true"
      - "traefik.http.routers.kanboard.tls.certresolver=myresolver"

  db:
    image: postgres:latest
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: kanboard
      POSTGRES_PASSWORD: kanboard-secret
      POSTGRES_DB: kanboard
    volumes:
      - db:/var/lib/postgresql
    # provided by kanboard
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kanboard"]
      start_period: 15s
      interval: 10s
      timeout: 5s

volumes:
  data:
    driver: local
  plugins:
    driver: local
  certs:
    driver: local
  db:
    driver: local

# so "external" means, "it already exsits, don't create one"
networks:
  proxy:
    external: true
  internal:
    driver: bridge # for app to db communication, no need to expose to traefik
