#ENC[AES256_GCM,data:RmI+EcYuT9r6XM6svg==,iv:Ntl5gvPCw7tE41YyZmxn/IaSXTmalQbCfEGTWh8k3Zw=,tag:X1xzS0aWgwoSAvcqXW8k9g==,type:comment]
vault_vps_ssh_port: ENC[AES256_GCM,data:SU9LNZw=,iv:ujpcBBz1PkWeZR7+IbrvP070If8beom9j5bhiazvWrE=,tag:bQunz3Uv7TYcsBwm00wGEw==,type:int]
vault_vps_ssh_user: ENC[AES256_GCM,data:wHuFZqh1,iv:xpLnoANUQe1c+LHD1SO135OvL5D7rJqZD2ximcjDhSo=,tag:EXSxWEzmheyMLow1uQXEUg==,type:str]
vault_vps_secondary_domain: ENC[AES256_GCM,data:coU2++arLVyo2rsz,iv:4cRUm/ksZqPdK8EjSc3fBrMTk6wwKI1K4uDxRv/5bus=,tag:eFuv2NtBlEV2MSVzJQjNxA==,type:str]
vault_vps_main_domain: ENC[AES256_GCM,data:DdlosvVgj0ELwA==,iv:fUHL/WPskEAQQKZ6aTXtaN6GJBR/FHOgN5ge9Ygp5v4=,tag:KDSQCagg6JoHAd344S2cNw==,type:str]
vault_vps_ssh_key_path: ENC[AES256_GCM,data:KsLWqemN/tW1LmzB8bqN3xE=,iv:RlztNmZZHIthiwfgFPqFboxxU0IbGSKS8p9kUqyja+c=,tag:tCdCX/IgNwUnCaZQI3qEZQ==,type:str]
vault_vps_human_user: ENC[AES256_GCM,data:vO+dthHD,iv:cqaD/zSr9CZtX+cLBUvSbYuBZBI0RczgbdSyUjPWuJk=,tag:NZ3CvixLvkm3fyaTOWb5Bw==,type:str]
#ENC[AES256_GCM,data:H8BBEB8Bqe52I+oqi3l+CwibmDwrLetZd24IsNc+,iv:LA7l+Jl4jVuu31d25LdHvzoRlHQCBKTkV39wYxGgVH4=,tag:F8CQrtCee86jEZbIUxxwmg==,type:comment]
vault_restic_aws_access_key_id: ENC[AES256_GCM,data:NHgyzrEWisVlCQ36n3r6B+kgD/tR+OBimQ==,iv:RR0zTNb3bb3ITzu7NHMYkO8JXr3LhhkSN+cuxmYQLJE=,tag:QaI6IjpOeyuD8oXRzq1oig==,type:str]
vault_restic_aws_secret_access_key: ENC[AES256_GCM,data:m09dUpShA8D+QLZoMFb484x3LBpE7jSp7NTGdNL6wg==,iv:LMy0MBRY1XEP2u0tRe9XbCa2JdIlEVLhxSfYWeQ19gk=,tag:IPjgB1JPSj4qcKoQslsgnA==,type:str]
vault_restic_password: ENC[AES256_GCM,data:pQsv7YCWbmDPAdKTRmFL3w==,iv:M4y2YDcE4nuCMWpxHCm7qbINCeY5O62vkGds0bFO9mE=,tag:pSjk202OU3SQS8l3lpfZNQ==,type:str]
sops:
    age:
        - recipient: age1ruahkq3p0tdx7qeqmtcxktysw0uanj5az05lz6n77cr6wksqtyashple88
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Qm5vS1hGUWZmbVgxbG51
            Q3FKVE5hNWF4dGFydzJHcWpBZ1RmVW5ZM2tRCndWYWIySFc4ZWl1ODJRV1VEWG84
            UVg1bmFhd1FrdEc4Y2pmSlFUQjJkR3MKLS0tIEJXYy9TczVhRFluYXZrSStlMU1y
            T0IyMnV4bWhBY0RHenQrV0tqQld3aEkKnXATjQ54iUQPnmTPO8KjpCm0fIJP6OXO
            zjcz3v3QG06CsMG+fJy5/8JiZtOQg1b+DNgN4CTAMAL7AQ1D10ocew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T09:48:12Z"
    mac: ENC[AES256_GCM,data:qpA98E3Rl5rMjRN98rkPi8xOkuiX64hyXsFUEp9goeScyAOH0sIZStda5Pjba7NyIp+XIE2SOmMCb48aPn9qeMDWcnbzO5y0tkR8SzX5i75I7JVBD93RaHmNYEUVbNTBtuUeoBHkDvjdOecyrk8Qq8YQjY3t69YQ83BiGQaALRY=,iv:oibSU8ar1wbf7u5xxqd/kJLZIsxKuQSGVJAjGy0POB0=,tag:FZON2vgo2hUQgMFmaNr9pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
