restic_aws_endpoint: "s3.eu-central-003.backblazeb2.com"
restic_aws_bucket: "vps-restic-9843"
restic_keep_last: 2
restic_keep_hourly: 1
restic_keep_daily: 7
restic_keep_weekly: 2
restic_keep_monthly: 6
restic_keep_yearly: 0
restic_backup_path: "/var/lib/docker/volumes"
