---
# secrets handled with ansible vault

all:
  children:
    stable:
      hosts:
        vps-main:
          ansible_user: "{{ vault_vps_ssh_user | default('root') }}"
          ansible_port: "{{ vault_vps_ssh_port | default(22) }}"
          ansible_host: "{{ vault_vps_main_domain }}"
    instance:
      hosts:
        ec2:
          ansible_user: ubuntu
          ansible_port: 22
          ansible_host: "{{ vault_vps_secondary_domain }}"
