---
# secrets handled with ansible vault

stable: # main VPS I already bought
  hosts:
    vps-main:
      ansible_host: "{{ vps_main_ip }}"
      ansible_user: "{{ vps_ssh_user }}"
      ansible_port: "{{ vps_ssh_port }}"
      ansible_ssh_private_key_file: "{{ vps_ssh_key_path }}"

dev: # for terraform provisioned VPS
  hosts:
    vps-test:
      ansible_host: "{{ vps_test_ip }}"
      ansible_user: "{{ vps_ssh_user }}"
      ansible_port: "{{ vps_ssh_port }}"
      ansible_ssh_private_key_file: "{{ vps_ssh_key_path }}"
