name: Yaml linter

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo to runner
        uses: actions/checkout@v4
      - name: Run the linter
        id: yamllint # used to refrence output later
        uses: frenck/action-yamllint@v1
